GB 5 add parser json (in work)
GeekbrainTeam/StockTipsApp pull request #7
Opened 2022-06-29 21:03 UTC by pfrost982

ретрофит работает, возвращает список компаний...

2022-06-30 12:54 UTC, GeekbrainTeam approved these changes

2022-07-01 17:54 UTC, MikhailKopylov requested changes

2022-07-01 17:54 UTC, MikhailKopylov commented on core/src/main/java/com/amk/core/entity/DateUtil.kt
> +
Я думаю лучше переместить в папку core/utils

2022-07-01 17:54 UTC, MikhailKopylov commented on core/src/main/java/com/amk/core/repository/Repository.kt
> +
Лишняя строка

2022-07-02 04:10 UTC, GeekbrainTeam approved these changes

2022-07-02 04:20 UTC, MikhailKopylov approved these changes

2022-07-02 04:23 UTC, GeekbrainTeam approved these changes

2022-07-02 04:25 UTC, HayarovEd approved these changes

2022-07-02 04:27 UTC, GeekbrainTeam approved these changes

2022-07-02 04:39 UTC, merged