Ed2806
GeekbrainTeam/StockTipsApp pull request #8
Opened 2022-07-01 11:09 UTC by HayarovEd

Создал первый фрагмент, есть еще что по мелочам поправить

2022-07-01 15:04 UTC, GeekbrainTeam requested changes

2022-07-01 15:04 UTC, GeekbrainTeam commented on app/src/main/java/com/amk/stocktipsapp/ListCompanyFragment.kt
> +
Лишние две строки

2022-07-01 15:04 UTC, GeekbrainTeam commented on app/src/main/java/com/amk/stocktipsapp/ListCompanyFragment.kt
> +        val stateClickListener: ListCompaniesAdapter.OnStateClickListener =
Надо добавить строку.

2022-07-02 02:05 UTC, HayarovEd commented on app/src/main/java/com/amk/stocktipsapp/adapters/ListCompaniesHolder.kt
> +
исправил

2022-07-02 02:05 UTC, HayarovEd commented on app/src/main/java/com/amk/stocktipsapp/adapters/ListCompaniesHolder.kt
> +
исправил

2022-07-02 02:06 UTC, HayarovEd commented on app/src/main/java/com/amk/stocktipsapp/adapters/ListCompaniesHolder.kt
> +
исправил

2022-07-02 02:07 UTC, HayarovEd commented on app/src/main/java/com/amk/stocktipsapp/model/DialogSorting.kt
> +
исправил

2022-07-02 02:11 UTC, HayarovEd commented on app/src/main/res/layout/fragment_list_company.xml
> +        android:layout_width="wrap_content"
Не очень хорошее решение, но поправал

2022-07-02 02:13 UTC, HayarovEd commented on app/src/main/res/layout/item_company.xml
> +    <com.google.android.material.checkbox.MaterialCheckBox
Исправил

2022-07-02 02:13 UTC, HayarovEd commented on app/src/main/java/com/amk/stocktipsapp/ListCompanyFragment.kt
> +
Исправил

2022-07-02 02:14 UTC, HayarovEd commented on app/src/main/java/com/amk/stocktipsapp/ListCompanyFragment.kt
> +    private fun setRecyclerView(list: List<FakeModel>) {
Исправил

2022-07-02 03:32 UTC, GeekbrainTeam approved these changes

2022-07-02 03:50 UTC, merged